/**
 * Single source of truth for all calculator categories and entries.
 * Used by: CalcLayout (sidebar), Footer (links), app/page.js (homepage cards)
 */
export const CATEGORIES = [
  {
    key: 'date',
    label: '날짜 · 시간',
    icon: '📅',
    color: 'from-amber-400 to-orange-400',
    labelColor: 'text-amber-600',
    border: 'border-amber-200',
    bg: 'bg-amber-50',
    desc: '날짜 계산의 모든 것',
    calcs: [
      { name: 'D-day 계산기',     url: '/cal/dday/',          icon: '📅', desc: '특정 날짜까지 남은 일수와 경과 일수를 계산해요', color: 'from-amber-400 to-orange-400' },
      { name: '날짜 차이 계산기',  url: '/cal/date-diff/',     icon: '📆', desc: '두 날짜 사이 일수·주·월·년을 한눈에 확인해요',   color: 'from-yellow-400 to-amber-400' },
      { name: '날짜 더하기/빼기',  url: '/cal/date-add/',      icon: '➕', desc: '날짜에 원하는 기간을 더하거나 빼서 결과를 계산해요', color: 'from-orange-400 to-rose-400' },
      { name: '영업일 계산기',     url: '/cal/business-days/', icon: '💼', desc: '주말·공휴일 제외한 실제 근무 가능 일수를 계산해요', color: 'from-lime-400 to-green-400' },
      { name: '만 나이 계산기',    url: '/cal/age/',           icon: '🎂', desc: '생년월일로 법적 만 나이를 정확하게 계산해요',       color: 'from-sky-400 to-blue-400' },
      { name: '기념일 계산기',     url: '/cal/anniversary/',   icon: '💑', desc: '100일·200일·1주년 등 기념일 날짜를 자동 계산해요',  color: 'from-pink-400 to-rose-400' },
      { name: '양력 음력 변환기',  url: '/cal/lunar/',         icon: '🌙', desc: '양력↔음력을 서로 변환하고 간지(갑자)까지 확인해요',   color: 'from-indigo-400 to-blue-500' },
    ],
  },
  {
    key: 'health',
    label: '건강 · 신체',
    icon: '💪',
    color: 'from-emerald-400 to-teal-400',
    labelColor: 'text-emerald-600',
    border: 'border-emerald-200',
    bg: 'bg-emerald-50',
    desc: '내 몸을 숫자로 이해해요',
    calcs: [
      { name: '적정 체중 계산기',  url: '/cal/weight/',   icon: '⚖️', desc: 'BMI와 표준 체중으로 나의 적정 체중 범위를 확인해요',         color: 'from-cyan-400 to-sky-500' },
      { name: '기초대사량 계산기', url: '/cal/calorie/',  icon: '🔥', desc: '나이·키·체중·활동량으로 하루 필요 칼로리를 계산해요',         color: 'from-rose-400 to-orange-400' },
      { name: '생리주기 계산기',   url: '/cal/period/',   icon: '🌸', desc: '다음 생리 예정일·배란일·가임기·PMS를 한 번에 예측해요',       color: 'from-pink-400 to-rose-500' },
    ],
  },
  {
    key: 'finance',
    label: '금융 · 급여',
    icon: '💰',
    color: 'from-green-400 to-emerald-500',
    labelColor: 'text-green-600',
    border: 'border-green-200',
    bg: 'bg-green-50',
    desc: '돈 계산을 정확하게',
    calcs: [
      { name: '월급 실수령액 계산기', url: '/cal/salary/',       icon: '💰', desc: '4대보험·소득세 공제 후 실제 통장에 들어오는 금액을 계산해요', color: 'from-emerald-400 to-green-500' },
      { name: '퇴직금 계산기',       url: '/cal/severance/',    icon: '💼', desc: '입사일·퇴직일·월급여로 법정 퇴직금을 바로 계산해요',        color: 'from-green-400 to-teal-500' },
      { name: '실업급여 계산기',     url: '/cal/unemployment/', icon: '📋', desc: '가입기간·나이·월급으로 구직급여 수령액과 지급일수를 계산해요', color: 'from-blue-400 to-indigo-500' },
      { name: '시급 계산기',         url: '/cal/hourly/',        icon: '⏰', desc: '2026 최저시급 기준으로 일급·주급·월급·연봉을 주휴수당 포함 계산해요', color: 'from-green-400 to-teal-500' },
      { name: '대출 이자 계산기',    url: '/cal/loan/',          icon: '🏦', desc: '원리금균등·원금균등·만기일시 상환 방식별 월 납입금과 총 이자를 계산해요', color: 'from-green-500 to-emerald-600' },
      { name: '부가세 계산기',       url: '/cal/vat/',           icon: '🧾', desc: '공급가액으로 부가세·합계금액을 계산하거나 합계금액에서 공급가액을 역산해요', color: 'from-teal-400 to-green-500' },
      { name: '종합소득세 계산기',   url: '/cal/income-tax/',    icon: '📊', desc: '근로·사업·프리랜서 소득을 입력하면 과세표준·세액공제·결정세액을 단계별로 계산해요', color: 'from-emerald-500 to-green-600' },
    ],
  },
  {
    key: 'life',
    label: '운세 · 라이프',
    icon: '✨',
    color: 'from-violet-400 to-purple-500',
    labelColor: 'text-violet-600',
    border: 'border-violet-200',
    bg: 'bg-violet-50',
    desc: '생활 속 재미있는 계산',
    calcs: [
      { name: '띠/별자리 계산기', url: '/cal/zodiac/', icon: '🐾', desc: '생년월일로 나의 띠와 별자리, 오행, 궁합까지 확인해요',          color: 'from-violet-400 to-purple-500' },
      { name: 'MBTI 궁합 계산기', url: '/cal/mbti/',   icon: '💘', desc: '두 사람의 MBTI를 선택하면 궁합 점수와 황금비율 여부를 알려드려요', color: 'from-pink-400 to-rose-500' },
      { name: '로또 추첨기',  url: '/cal/lotto/',  icon: '🎱', desc: '행운의 로또 번호를 추첨해요. 제외 번호 설정 지원', color: 'from-violet-500 to-indigo-500' },
    ],
  },
  {
    key: 'utility',
    label: '유틸리티',
    icon: '🛠️',
    color: 'from-sky-400 to-blue-500',
    labelColor: 'text-sky-600',
    border: 'border-sky-200',
    bg: 'bg-sky-50',
    desc: '글자수·단위 변환 등 실용 도구',
    calcs: [
      { name: '글자수 세기', url: '/cal/char-count/', icon: '✍️', desc: '공백 포함/제외·바이트·단어 수를 실시간으로 계산해요. 자소서·SNS 글자 제한도 바로 확인해요', color: 'from-sky-400 to-blue-500' },
      { name: '평수 계산기', url: '/cal/pyeong/',     icon: '📐', desc: '평↔m² 즉시 변환 및 아파트 평형 참고표. 공급면적·전용면적 기준도 안내해요',             color: 'from-sky-500 to-indigo-500' },
      { name: '단위 변환기', url: '/cal/unit/',        icon: '🔄', desc: '길이·무게·온도·넓이·부피·속도·데이터 단위를 한 번에 변환해요',                          color: 'from-teal-400 to-cyan-500' },
    ],
  },
]
